"""recreate users and reports

Revision ID: 27f2ff2d5ef6
Revises: 8a9ceb4a433f
Create Date: 2026-06-10 08:50:02.192397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f2ff2d5ef6'
down_revision: Union[str, Sequence[str], None] = '8a9ceb4a433f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
