"""add_current_agent_to_reports

Revision ID: 65e052bf076f
Revises: db4170c32c24
Create Date: 2026-06-18 14:45:12.322037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65e052bf076f'
down_revision: Union[str, Sequence[str], None] = 'db4170c32c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('current_agent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'current_agent')
    # ### end Alembic commands ###
